//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecepecionMSW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Numeros_Serie
    {
        public int Id_NSerie { get; set; }
        public int Id_Persona { get; set; }
        public string NumSerieCampeon { get; set; }
        public string NumSerieSmart { get; set; }
        public System.DateTime Fecha { get; set; }
    
        public virtual Persona Persona { get; set; }
    }
}
