//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecepecionMSW.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Persona
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Persona()
        {
            this.Registro_Llamadas = new HashSet<Registro_Llamadas>();
            this.Numeros_Serie = new HashSet<Numeros_Serie>();
        }
    
        public int Id_Persona { get; set; }
        [Required(ErrorMessage = "El nombre debe ser completado")]
        [StringLength(100)]
        public string Nombre { get; set; }
        [Required(ErrorMessage = "Ingrese el numero fijo")]
        [MinLength(10), MaxLength(10)]
        public string TelefonoFijo { get; set; }
        [MinLength(10), MaxLength(10)]
        public string TelefonoCelular { get; set; }
        [Required(ErrorMessage = "El correo es obligatorio")]
        [EmailAddress]
        public string Correo { get; set; }
        public string Empresa { get; set; }
        public string Dependencia { get; set; }
        public string LadaCelular { get; set; }
        public string LadaFijo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Registro_Llamadas> Registro_Llamadas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Numeros_Serie> Numeros_Serie { get; set; }
    }
}
