//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecepecionMSW.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RecepcionMSWEntities : DbContext
    {
        public RecepcionMSWEntities()
            : base("name=RecepcionMSWEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<LLamada_Catalogo> LLamada_Catalogo { get; set; }
        public virtual DbSet<Persona> Personas { get; set; }
        public virtual DbSet<Registro_Llamadas> Registro_Llamadas { get; set; }
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<Atendio_Catalogo> Atendio_Catalogo { get; set; }
        public virtual DbSet<Realizo_Recibio_Llamada_Catalogo> Realizo_Recibio_Llamada_Catalogo { get; set; }
        public virtual DbSet<Numeros_Serie> Numeros_Serie { get; set; }
    }
}
